<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250911103803 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE freedict_catalog DROP CONSTRAINT freedict_catalog_pkey');
        $this->addSql('ALTER TABLE freedict_catalog DROP id');
        $this->addSql('ALTER TABLE freedict_catalog ADD PRIMARY KEY (name)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE freedict_catalog DROP CONSTRAINT freedict_catalog_pkey');
        $this->addSql('ALTER TABLE freedict_catalog ADD id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL');
        $this->addSql('ALTER TABLE freedict_catalog ADD PRIMARY KEY (id)');
    }
}
