<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250823165123 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE dictionary (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(63) NOT NULL, edition VARCHAR(32) DEFAULT NULL, release_version VARCHAR(32) DEFAULT NULL, release_date VARCHAR(32) DEFAULT NULL, tei_url TEXT DEFAULT NULL, src_id INT NOT NULL, dst_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_1FA0E526FF529AC ON dictionary (src_id)');
        $this->addSql('CREATE INDEX IDX_1FA0E526E1885D19 ON dictionary (dst_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_dictionary_name ON dictionary (name)');
        $this->addSql('CREATE TABLE freedict_catalog (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(63) NOT NULL, src VARCHAR(16) NOT NULL, dst VARCHAR(16) NOT NULL, edition VARCHAR(32) DEFAULT NULL, headwords INT DEFAULT NULL, maintainer_name VARCHAR(255) DEFAULT NULL, source_url VARCHAR(255) DEFAULT NULL, status VARCHAR(64) DEFAULT NULL, best_url TEXT DEFAULT NULL, best_platform VARCHAR(16) DEFAULT NULL, release_date VARCHAR(32) DEFAULT NULL, release_version VARCHAR(32) DEFAULT NULL, release_size BIGINT DEFAULT NULL, raw JSON DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_fdc_name ON freedict_catalog (name)');
        $this->addSql('CREATE TABLE lang (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code3 VARCHAR(3) NOT NULL, code2 VARCHAR(2) DEFAULT NULL, name VARCHAR(80) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_lang_code3 ON lang (code3)');
        $this->addSql('CREATE UNIQUE INDEX uniq_lang_code2 ON lang (code2)');
        $this->addSql('CREATE TABLE lemma (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, headword VARCHAR(255) NOT NULL, norm_headword VARCHAR(255) NOT NULL, pos VARCHAR(16) DEFAULT NULL, gender VARCHAR(1) DEFAULT NULL, features JSON DEFAULT NULL, rank INT DEFAULT NULL, language_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_3CF1763782F1BAF4 ON lemma (language_id)');
        $this->addSql('CREATE INDEX IDX_3CF17637F20DA05A ON lemma (headword)');
        $this->addSql('CREATE INDEX IDX_3CF176371934F673 ON lemma (norm_headword)');
        $this->addSql('CREATE UNIQUE INDEX uniq_lang_head_pos ON lemma (language_id, headword, pos)');
        $this->addSql('CREATE TABLE sense (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, gloss TEXT DEFAULT NULL, examples JSON DEFAULT NULL, rank INT DEFAULT NULL, raw JSON DEFAULT NULL, lemma_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_F2B33FBF4BA2AE3 ON sense (lemma_id)');
        $this->addSql('CREATE TABLE translation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, rank INT DEFAULT NULL, meta JSON DEFAULT NULL, src_lemma_id INT NOT NULL, dst_lemma_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B469456F88ECBA07 ON translation (src_lemma_id)');
        $this->addSql('CREATE INDEX IDX_B469456FF490FB25 ON translation (dst_lemma_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_src_dst ON translation (src_lemma_id, dst_lemma_id)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0 ON messenger_messages (queue_name)');
        $this->addSql('CREATE INDEX IDX_75EA56E0E3BD61CE ON messenger_messages (available_at)');
        $this->addSql('CREATE INDEX IDX_75EA56E016BA31DB ON messenger_messages (delivered_at)');
        $this->addSql('ALTER TABLE dictionary ADD CONSTRAINT FK_1FA0E526FF529AC FOREIGN KEY (src_id) REFERENCES lang (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE dictionary ADD CONSTRAINT FK_1FA0E526E1885D19 FOREIGN KEY (dst_id) REFERENCES lang (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE lemma ADD CONSTRAINT FK_3CF1763782F1BAF4 FOREIGN KEY (language_id) REFERENCES lang (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE sense ADD CONSTRAINT FK_F2B33FBF4BA2AE3 FOREIGN KEY (lemma_id) REFERENCES lemma (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE translation ADD CONSTRAINT FK_B469456F88ECBA07 FOREIGN KEY (src_lemma_id) REFERENCES lemma (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE translation ADD CONSTRAINT FK_B469456FF490FB25 FOREIGN KEY (dst_lemma_id) REFERENCES lemma (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE dictionary DROP CONSTRAINT FK_1FA0E526FF529AC');
        $this->addSql('ALTER TABLE dictionary DROP CONSTRAINT FK_1FA0E526E1885D19');
        $this->addSql('ALTER TABLE lemma DROP CONSTRAINT FK_3CF1763782F1BAF4');
        $this->addSql('ALTER TABLE sense DROP CONSTRAINT FK_F2B33FBF4BA2AE3');
        $this->addSql('ALTER TABLE translation DROP CONSTRAINT FK_B469456F88ECBA07');
        $this->addSql('ALTER TABLE translation DROP CONSTRAINT FK_B469456FF490FB25');
        $this->addSql('DROP TABLE dictionary');
        $this->addSql('DROP TABLE freedict_catalog');
        $this->addSql('DROP TABLE lang');
        $this->addSql('DROP TABLE lemma');
        $this->addSql('DROP TABLE sense');
        $this->addSql('DROP TABLE translation');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
